### ISSUE TITLE
cli does not respect --max-file-duration

### ISSUE THREAD

**Issue by abfleishman** [ConservationMetrics/audiomoth-utils-cli#1]
The cli works as expected when run without specifying `--max-file-duration`, however when specifying `--max-file-duration 5` if does not expand files but instead writes a single file.  

## example cli command run on Windows `cmd` 

This works as expected, writing 2000+ 5 second files
```cmd
D:/git_repos/cmitools/inst/audiomoth-utils.exe expand-duration "//NAS2/NAS6_5Jun17/Sounds/BCI_Rapid_2024_R1/test_dataID/GRTS 180/Hurricane Creek/20230612_200000T.WAV" -d "//NAS2/NAS6_5Jun17/Sounds/BCI_Rapid_2024_R1/test_dataID/GRTS 180/Hurricane Creek"
```

This writes a single large file
```cmd
D:/git_repos/cmitools/inst/audiomoth-utils.exe expand-duration "//NAS2/NAS6_5Jun17/Sounds/BCI_Rapid_2024_R1/test_dataID/GRTS 180/Hurricane Creek/20230612_200000T.WAV" -d "//NAS2/NAS6_5Jun17/Sounds/BCI_Rapid_2024_R1/test_dataID/GRTS 180/Hurricane Creek" --max-file-duration 5
```

**Comment by IamJeffG** [comment]
I have identified the cause as https://github.com/tj/commander.js/issues/834.  Will work on a fix.

**Comment by IamJeffG** [comment]
@abfleishman this should be fixed in https://github.com/ConservationMetrics/audiomoth-utils-cli/releases/tag/v24071616-1.5.0

Please install and report back!

**Comment by abfleishman** [comment]
@IamJeffG I am seeing this message:
```
 [1] "Expansion completed successfully."                                            
 [2] "pkg/prelude/bootstrap.js:1926"                                                
 [3] "      return wrapper.apply(this.exports, args);"                              
 [4] "                     ^"                                                       
 [5] ""                                                                             
 [6] "TypeError: Cannot read property 'then' of undefined"                          
 [7] "    at Object.<anonymous> (C:\\snapshot\\project\\bin\\cli.js)"               
 [8] "    at Module._compile (pkg/prelude/bootstrap.js:1926:22)"                    
 [9] "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)"
[10] "    at Module.load (internal/modules/cjs/loader.js:950:32)"                   
[11] "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)"         
[12] "    at Function.runMain (pkg/prelude/bootstrap.js:1979:12)"                   
[13] "    at internal/main/run_main_module.js:17:47"
```

**Comment by IamJeffG** [comment]
Thanks for reporting. https://github.com/ConservationMetrics/audiomoth-utils-cli/releases/tag/v24071619-1.5.0 fixes that warning.

Meantime, any exports with the previous `v24071616-1.5.0` version are still correct.

**Comment by abfleishman** [comment]
Ok that seems to be working!Thank @IamJeffG
